version: '2'
services:
  postgres:
    image: postgres:9.6.2
    ports:
      - "5432"
  web:
    build: .
    env_file:
      - .env
    depends_on:
      - postgres
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/school-evaluate
    ports:
      - "3000:3000"
